### ISSUE TITLE
calling reverso commands from elisp

### ISSUE THREAD

**Issue by mooseyboots** [SqrtMinusOne/reverso.el#1]
hi, thanks for this great package, nice work!

i have a simple question, i just don't know the answer because i don't know transient.el: can i call reverso commands from elisp with a query?

so the priority wd go a) elisp arg, then as per your readme: b) word-at-point, c) region, d) buffer, as per usual...

i translate in emacs and while transient is wonderful, i prefer instant results with look-ups rather than having to set options before i see anything.

i tried a hack like so, is this the way to go about it?:

```
(reverso--translate query source target
                    (lambda (data)
                      (reverso--with-buffer
                       ;; remove is-brief here for now
                          (reverso--translate-render query data))))
```

**Comment by SqrtMinusOne** [comment]
Yeah, pretty much that.

You can write a wrapper function around `reverso--translate` like that, bind that to the key you want. Makes sense if you do some particular kind of translation a lot of times.

**Comment by martianhi** [comment]
thanks for the answer.

yeah i got it working and added to [wordreference.el](https://codeberg.org/martianh/wordreference.el).
